/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriasRouteRouteImport } from './routes/categorias/route'
import { Route as MarcasRouteRouteImport } from './routes/marcas/route'
import { Route as ProdutosRouteRouteImport } from './routes/produtos/route'
import { Route as CategoriasIndexRouteImport } from './routes/categorias/index'
import { Route as CategoriasSlugRouteImport } from './routes/categorias/$slug'
import { Route as ProdutosIndexRouteImport } from './routes/produtos/index'
import { Route as ProdutosIdRouteImport } from './routes/produtos/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRouteRoute = CategoriasRouteRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasRouteRoute = MarcasRouteRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRouteRoute = ProdutosRouteRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasIndexRoute = CategoriasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriasRouteRoute,
} as any)
const CategoriasSlugRoute = CategoriasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriasRouteRoute,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProdutosRouteRoute,
} as any)
const ProdutosIdRoute = ProdutosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProdutosRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRouteRouteWithChildren
  '/marcas': typeof MarcasRouteRoute
  '/produtos': typeof ProdutosRouteRouteWithChildren
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/produtos/$id': typeof ProdutosIdRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/marcas': typeof MarcasRouteRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/produtos/$id': typeof ProdutosIdRoute
  '/categorias': typeof CategoriasIndexRoute
  '/produtos': typeof ProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRouteRouteWithChildren
  '/marcas': typeof MarcasRouteRoute
  '/produtos': typeof ProdutosRouteRouteWithChildren
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/produtos/$id': typeof ProdutosIdRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categorias'
    | '/marcas'
    | '/produtos'
    | '/categorias/$slug'
    | '/produtos/$id'
    | '/categorias/'
    | '/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/marcas'
    | '/categorias/$slug'
    | '/produtos/$id'
    | '/categorias'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/categorias'
    | '/marcas'
    | '/produtos'
    | '/categorias/$slug'
    | '/produtos/$id'
    | '/categorias/'
    | '/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriasRouteRoute: typeof CategoriasRouteRouteWithChildren
  MarcasRouteRoute: typeof MarcasRouteRoute
  ProdutosRouteRoute: typeof ProdutosRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/': {
      id: '/categorias/'
      path: '/'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriasIndexRouteImport
      parentRoute: typeof CategoriasRouteRoute
    }
    '/categorias/$slug': {
      id: '/categorias/$slug'
      path: '/$slug'
      fullPath: '/categorias/$slug'
      preLoaderRoute: typeof CategoriasSlugRouteImport
      parentRoute: typeof CategoriasRouteRoute
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof ProdutosRouteRoute
    }
    '/produtos/$id': {
      id: '/produtos/$id'
      path: '/$id'
      fullPath: '/produtos/$id'
      preLoaderRoute: typeof ProdutosIdRouteImport
      parentRoute: typeof ProdutosRouteRoute
    }
  }
}

interface CategoriasRouteRouteChildren {
  CategoriasSlugRoute: typeof CategoriasSlugRoute
  CategoriasIndexRoute: typeof CategoriasIndexRoute
}

const CategoriasRouteRouteChildren: CategoriasRouteRouteChildren = {
  CategoriasSlugRoute: CategoriasSlugRoute,
  CategoriasIndexRoute: CategoriasIndexRoute,
}

const CategoriasRouteRouteWithChildren = CategoriasRouteRoute._addFileChildren(
  CategoriasRouteRouteChildren,
)

interface ProdutosRouteRouteChildren {
  ProdutosIdRoute: typeof ProdutosIdRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

const ProdutosRouteRouteChildren: ProdutosRouteRouteChildren = {
  ProdutosIdRoute: ProdutosIdRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}

const ProdutosRouteRouteWithChildren = ProdutosRouteRoute._addFileChildren(
  ProdutosRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriasRouteRoute: CategoriasRouteRouteWithChildren,
  MarcasRouteRoute: MarcasRouteRoute,
  ProdutosRouteRoute: ProdutosRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
