/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as CategoriasRouteRouteImport } from './routes/categorias/route'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as MarcasRouteRouteImport } from './routes/marcas/route'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ProdutosRouteRouteImport } from './routes/produtos/route'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as CategoriasIndexRouteImport } from './routes/categorias/index'
import { Route as CategoriasSlugRouteImport } from './routes/categorias/$slug'
import { Route as MarcasIndexRouteImport } from './routes/marcas/index'
import { Route as MarcasSlugRouteImport } from './routes/marcas/$slug'
import { Route as ProdutosIndexRouteImport } from './routes/produtos/index'
import { Route as ProdutosIdRouteImport } from './routes/produtos/$id'
import { Route as AdminImportacoesIndexRouteImport } from './routes/admin/importacoes/index'
import { Route as AdminImportacoesIdRouteImport } from './routes/admin/importacoes/$id'
import { Route as AdminImportacoesNovaRouteImport } from './routes/admin/importacoes/nova'
import { Route as AdminImportacoesPreviewRouteImport } from './routes/admin/importacoes/preview'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin/produtos/index'
import { Route as AdminProdutosIdRouteImport } from './routes/admin/produtos/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRouteRoute = CategoriasRouteRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasRouteRoute = MarcasRouteRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRouteRoute = ProdutosRouteRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CategoriasIndexRoute = CategoriasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriasRouteRoute,
} as any)
const CategoriasSlugRoute = CategoriasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriasRouteRoute,
} as any)
const MarcasIndexRoute = MarcasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarcasRouteRoute,
} as any)
const MarcasSlugRoute = MarcasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarcasRouteRoute,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProdutosRouteRoute,
} as any)
const ProdutosIdRoute = ProdutosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProdutosRouteRoute,
} as any)
const AdminImportacoesIndexRoute = AdminImportacoesIndexRouteImport.update({
  id: '/importacoes/',
  path: '/importacoes/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminImportacoesIdRoute = AdminImportacoesIdRouteImport.update({
  id: '/importacoes/$id',
  path: '/importacoes/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminImportacoesNovaRoute = AdminImportacoesNovaRouteImport.update({
  id: '/importacoes/nova',
  path: '/importacoes/nova',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminImportacoesPreviewRoute = AdminImportacoesPreviewRouteImport.update({
  id: '/importacoes/preview',
  path: '/importacoes/preview',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProdutosIdRoute = AdminProdutosIdRouteImport.update({
  id: '/produtos/$id',
  path: '/produtos/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/categorias': typeof CategoriasRouteRouteWithChildren
  '/marcas': typeof MarcasRouteRouteWithChildren
  '/produtos': typeof ProdutosRouteRouteWithChildren
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/orcamento': typeof OrcamentoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/login': typeof AdminLoginRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/marcas/$slug': typeof MarcasSlugRoute
  '/produtos/$id': typeof ProdutosIdRoute
  '/admin/': typeof AdminIndexRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/marcas/': typeof MarcasIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/admin/importacoes/$id': typeof AdminImportacoesIdRoute
  '/admin/importacoes/nova': typeof AdminImportacoesNovaRoute
  '/admin/importacoes/preview': typeof AdminImportacoesPreviewRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/importacoes/': typeof AdminImportacoesIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/orcamento': typeof OrcamentoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/login': typeof AdminLoginRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/marcas/$slug': typeof MarcasSlugRoute
  '/produtos/$id': typeof ProdutosIdRoute
  '/admin': typeof AdminIndexRoute
  '/categorias': typeof CategoriasIndexRoute
  '/marcas': typeof MarcasIndexRoute
  '/produtos': typeof ProdutosIndexRoute
  '/admin/importacoes/$id': typeof AdminImportacoesIdRoute
  '/admin/importacoes/nova': typeof AdminImportacoesNovaRoute
  '/admin/importacoes/preview': typeof AdminImportacoesPreviewRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/importacoes': typeof AdminImportacoesIndexRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/categorias': typeof CategoriasRouteRouteWithChildren
  '/marcas': typeof MarcasRouteRouteWithChildren
  '/produtos': typeof ProdutosRouteRouteWithChildren
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/orcamento': typeof OrcamentoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/login': typeof AdminLoginRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/marcas/$slug': typeof MarcasSlugRoute
  '/produtos/$id': typeof ProdutosIdRoute
  '/admin/': typeof AdminIndexRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/marcas/': typeof MarcasIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/admin/importacoes/$id': typeof AdminImportacoesIdRoute
  '/admin/importacoes/nova': typeof AdminImportacoesNovaRoute
  '/admin/importacoes/preview': typeof AdminImportacoesPreviewRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/importacoes/': typeof AdminImportacoesIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/categorias'
    | '/marcas'
    | '/produtos'
    | '/contato'
    | '/empresa'
    | '/orcamento'
    | '/privacidade'
    | '/termos-de-uso'
    | '/admin/login'
    | '/categorias/$slug'
    | '/marcas/$slug'
    | '/produtos/$id'
    | '/admin/'
    | '/categorias/'
    | '/marcas/'
    | '/produtos/'
    | '/admin/importacoes/$id'
    | '/admin/importacoes/nova'
    | '/admin/importacoes/preview'
    | '/admin/produtos/$id'
    | '/admin/importacoes/'
    | '/admin/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/empresa'
    | '/orcamento'
    | '/privacidade'
    | '/termos-de-uso'
    | '/admin/login'
    | '/categorias/$slug'
    | '/marcas/$slug'
    | '/produtos/$id'
    | '/admin'
    | '/categorias'
    | '/marcas'
    | '/produtos'
    | '/admin/importacoes/$id'
    | '/admin/importacoes/nova'
    | '/admin/importacoes/preview'
    | '/admin/produtos/$id'
    | '/admin/importacoes'
    | '/admin/produtos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/categorias'
    | '/marcas'
    | '/produtos'
    | '/contato'
    | '/empresa'
    | '/orcamento'
    | '/privacidade'
    | '/termos-de-uso'
    | '/admin/login'
    | '/categorias/$slug'
    | '/marcas/$slug'
    | '/produtos/$id'
    | '/admin/'
    | '/categorias/'
    | '/marcas/'
    | '/produtos/'
    | '/admin/importacoes/$id'
    | '/admin/importacoes/nova'
    | '/admin/importacoes/preview'
    | '/admin/produtos/$id'
    | '/admin/importacoes/'
    | '/admin/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CategoriasRouteRoute: typeof CategoriasRouteRouteWithChildren
  MarcasRouteRoute: typeof MarcasRouteRouteWithChildren
  ProdutosRouteRoute: typeof ProdutosRouteRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  EmpresaRoute: typeof EmpresaRoute
  OrcamentoRoute: typeof OrcamentoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/categorias/': {
      id: '/categorias/'
      path: '/'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriasIndexRouteImport
      parentRoute: typeof CategoriasRouteRoute
    }
    '/categorias/$slug': {
      id: '/categorias/$slug'
      path: '/$slug'
      fullPath: '/categorias/$slug'
      preLoaderRoute: typeof CategoriasSlugRouteImport
      parentRoute: typeof CategoriasRouteRoute
    }
    '/marcas/': {
      id: '/marcas/'
      path: '/'
      fullPath: '/marcas/'
      preLoaderRoute: typeof MarcasIndexRouteImport
      parentRoute: typeof MarcasRouteRoute
    }
    '/marcas/$slug': {
      id: '/marcas/$slug'
      path: '/$slug'
      fullPath: '/marcas/$slug'
      preLoaderRoute: typeof MarcasSlugRouteImport
      parentRoute: typeof MarcasRouteRoute
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof ProdutosRouteRoute
    }
    '/produtos/$id': {
      id: '/produtos/$id'
      path: '/$id'
      fullPath: '/produtos/$id'
      preLoaderRoute: typeof ProdutosIdRouteImport
      parentRoute: typeof ProdutosRouteRoute
    }
    '/admin/importacoes/': {
      id: '/admin/importacoes/'
      path: '/importacoes'
      fullPath: '/admin/importacoes/'
      preLoaderRoute: typeof AdminImportacoesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/importacoes/$id': {
      id: '/admin/importacoes/$id'
      path: '/importacoes/$id'
      fullPath: '/admin/importacoes/$id'
      preLoaderRoute: typeof AdminImportacoesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/importacoes/nova': {
      id: '/admin/importacoes/nova'
      path: '/importacoes/nova'
      fullPath: '/admin/importacoes/nova'
      preLoaderRoute: typeof AdminImportacoesNovaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/importacoes/preview': {
      id: '/admin/importacoes/preview'
      path: '/importacoes/preview'
      fullPath: '/admin/importacoes/preview'
      preLoaderRoute: typeof AdminImportacoesPreviewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/produtos/$id': {
      id: '/admin/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AdminProdutosIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminImportacoesIdRoute: typeof AdminImportacoesIdRoute
  AdminImportacoesNovaRoute: typeof AdminImportacoesNovaRoute
  AdminImportacoesPreviewRoute: typeof AdminImportacoesPreviewRoute
  AdminProdutosIdRoute: typeof AdminProdutosIdRoute
  AdminImportacoesIndexRoute: typeof AdminImportacoesIndexRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminImportacoesIdRoute: AdminImportacoesIdRoute,
  AdminImportacoesNovaRoute: AdminImportacoesNovaRoute,
  AdminImportacoesPreviewRoute: AdminImportacoesPreviewRoute,
  AdminProdutosIdRoute: AdminProdutosIdRoute,
  AdminImportacoesIndexRoute: AdminImportacoesIndexRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CategoriasRouteRouteChildren {
  CategoriasSlugRoute: typeof CategoriasSlugRoute
  CategoriasIndexRoute: typeof CategoriasIndexRoute
}

const CategoriasRouteRouteChildren: CategoriasRouteRouteChildren = {
  CategoriasSlugRoute: CategoriasSlugRoute,
  CategoriasIndexRoute: CategoriasIndexRoute,
}

const CategoriasRouteRouteWithChildren = CategoriasRouteRoute._addFileChildren(
  CategoriasRouteRouteChildren,
)

interface MarcasRouteRouteChildren {
  MarcasSlugRoute: typeof MarcasSlugRoute
  MarcasIndexRoute: typeof MarcasIndexRoute
}

const MarcasRouteRouteChildren: MarcasRouteRouteChildren = {
  MarcasSlugRoute: MarcasSlugRoute,
  MarcasIndexRoute: MarcasIndexRoute,
}

const MarcasRouteRouteWithChildren = MarcasRouteRoute._addFileChildren(
  MarcasRouteRouteChildren,
)

interface ProdutosRouteRouteChildren {
  ProdutosIdRoute: typeof ProdutosIdRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

const ProdutosRouteRouteChildren: ProdutosRouteRouteChildren = {
  ProdutosIdRoute: ProdutosIdRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}

const ProdutosRouteRouteWithChildren = ProdutosRouteRoute._addFileChildren(
  ProdutosRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CategoriasRouteRoute: CategoriasRouteRouteWithChildren,
  MarcasRouteRoute: MarcasRouteRouteWithChildren,
  ProdutosRouteRoute: ProdutosRouteRouteWithChildren,
  ContatoRoute: ContatoRoute,
  EmpresaRoute: EmpresaRoute,
  OrcamentoRoute: OrcamentoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
